-- Cykloservis: 11 tabulek. Pouze testovaci schema.
CREATE TABLE zakaznik (
    id_zakaznik NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    jmeno VARCHAR2(50) NOT NULL,
    prijmeni VARCHAR2(50) NOT NULL,
    telefon VARCHAR2(20),
    email VARCHAR2(100),
    adresa VARCHAR2(200),
    datum_registrace DATE DEFAULT TRUNC(CURRENT_DATE) NOT NULL,
    PRIMARY KEY (id_zakaznik),
    UNIQUE (email)
);

CREATE TABLE zamestnanec (
    id_zamestnanec NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    jmeno VARCHAR2(50) NOT NULL,
    prijmeni VARCHAR2(50) NOT NULL,
    pozice VARCHAR2(30) NOT NULL,
    telefon VARCHAR2(20),
    datum_nastupu DATE NOT NULL,
    PRIMARY KEY (id_zamestnanec)
);

CREATE TABLE dodavatel (
    id_dodavatel NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nazev VARCHAR2(100) NOT NULL,
    kontaktni_osoba VARCHAR2(100),
    telefon VARCHAR2(20),
    email VARCHAR2(100),
    PRIMARY KEY (id_dodavatel)
);

CREATE TABLE kolo (
    id_kolo NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_zakaznik NUMBER(10) NOT NULL,
    znacka VARCHAR2(50) NOT NULL,
    model VARCHAR2(50),
    typ VARCHAR2(30),
    rok_vyroby NUMBER(5),
    seriove_cislo VARCHAR2(50),
    PRIMARY KEY (id_kolo),
    UNIQUE (seriove_cislo),
    FOREIGN KEY (id_zakaznik) REFERENCES zakaznik (id_zakaznik)
);

CREATE TABLE elektrokolo (
    id_kolo NUMBER(10) NOT NULL,
    vyrobce_motoru VARCHAR2(80) NOT NULL,
    vykon_motoru_w NUMBER(10) NOT NULL,
    kapacita_baterie_wh NUMBER(8,2) NOT NULL,
    PRIMARY KEY (id_kolo),
    FOREIGN KEY (id_kolo) REFERENCES kolo (id_kolo),
    CHECK (vykon_motoru_w > 0),
    CHECK (kapacita_baterie_wh > 0)
);

CREATE TABLE sluzba (
    id_sluzba NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nazev VARCHAR2(100) NOT NULL,
    popis VARCHAR2(300),
    cena_zakladni NUMBER(10,2) NOT NULL,
    odhad_doby_min NUMBER(10),
    PRIMARY KEY (id_sluzba),
    CHECK (cena_zakladni >= 0),
    CHECK (odhad_doby_min IS NULL OR odhad_doby_min > 0)
);

CREATE TABLE dil (
    id_dil NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nazev VARCHAR2(100) NOT NULL,
    cena_prodejni NUMBER(10,2) NOT NULL,
    mnozstvi_sklad NUMBER(10) DEFAULT 0 NOT NULL,
    id_dodavatel NUMBER(10),
    PRIMARY KEY (id_dil),
    FOREIGN KEY (id_dodavatel) REFERENCES dodavatel (id_dodavatel),
    CHECK (cena_prodejni >= 0),
    CHECK (mnozstvi_sklad >= 0)
);

CREATE TABLE zakazka (
    id_zakazka NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_kolo NUMBER(10) NOT NULL,
    id_zamestnanec NUMBER(10),
    datum_prijeti TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    datum_dokonceni TIMESTAMP,
    stav VARCHAR2(20) DEFAULT 'přijato' NOT NULL,
    poznamka VARCHAR2(500),
    PRIMARY KEY (id_zakazka),
    FOREIGN KEY (id_kolo) REFERENCES kolo (id_kolo),
    FOREIGN KEY (id_zamestnanec) REFERENCES zamestnanec (id_zamestnanec),
    CHECK (stav IN ('přijato','v opravě','hotovo','vyzvednuto','stornováno')),
    CHECK (datum_dokonceni IS NULL OR datum_dokonceni >= datum_prijeti)
);

CREATE TABLE zakazka_sluzba (
    id_zakazka NUMBER(10) NOT NULL,
    id_sluzba NUMBER(10) NOT NULL,
    mnozstvi NUMBER(10) DEFAULT 1 NOT NULL,
    cena_za_jednotku NUMBER(10,2) NOT NULL,
    PRIMARY KEY (id_zakazka, id_sluzba),
    FOREIGN KEY (id_zakazka) REFERENCES zakazka (id_zakazka),
    FOREIGN KEY (id_sluzba) REFERENCES sluzba (id_sluzba),
    CHECK (mnozstvi > 0),
    CHECK (cena_za_jednotku >= 0)
);

CREATE TABLE zakazka_dil (
    id_zakazka NUMBER(10) NOT NULL,
    id_dil NUMBER(10) NOT NULL,
    mnozstvi NUMBER(10) DEFAULT 1 NOT NULL,
    cena_za_jednotku NUMBER(10,2) NOT NULL,
    PRIMARY KEY (id_zakazka, id_dil),
    FOREIGN KEY (id_zakazka) REFERENCES zakazka (id_zakazka),
    FOREIGN KEY (id_dil) REFERENCES dil (id_dil),
    CHECK (mnozstvi > 0),
    CHECK (cena_za_jednotku >= 0)
);

CREATE TABLE faktura (
    id_faktura NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_zakazka NUMBER(10) NOT NULL,
    datum_vystaveni DATE DEFAULT TRUNC(CURRENT_DATE) NOT NULL,
    castka_celkem NUMBER(10,2) NOT NULL,
    zpusob_platby VARCHAR2(20) NOT NULL,
    stav_platby VARCHAR2(20) DEFAULT 'nezaplaceno' NOT NULL,
    PRIMARY KEY (id_faktura),
    UNIQUE (id_zakazka),
    FOREIGN KEY (id_zakazka) REFERENCES zakazka (id_zakazka),
    CHECK (castka_celkem >= 0),
    CHECK (zpusob_platby IN ('hotově','kartou','převodem')),
    CHECK (stav_platby IN ('zaplaceno','nezaplaceno'))
);
