import {chromium} from 'playwright';
import fs from 'node:fs/promises';
const out=process.argv[2];await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:18763/');
await page.screenshot({path:out+'/app_home.png',fullPage:true});
await page.getByRole('button',{name:'Načíst demo',exact:true}).click();
await page.getByRole('heading',{name:'Pořadí podle vašich vstupů'}).waitFor();
await page.screenshot({path:out+'/app_results.png',fullPage:true});
await page.getByRole('link',{name:'Upravit preference'}).click();
if(await page.locator('select').count()!==76)throw Error('Expected 76 pairs');
await page.locator('select').first().selectOption('9');
await page.getByRole('button',{name:'Vypočítat pořadí →'}).click();
await page.getByRole('heading',{name:'Pořadí podle vašich vstupů'}).waitFor();
await page.setViewportSize({width:390,height:844});await page.goto('http://127.0.0.1:18763/');
await page.screenshot({path:out+'/app_mobile.png',fullPage:true});
if(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth))throw Error('Mobile overflow');
await browser.close();await fs.writeFile(out+'/browser_tests.json',JSON.stringify({status:'PASS',pair_count:76,errors},null,2));console.log('Browser checks PASS');
